### PR TITLE
Add clade definitions for 24A and 24B

### PR DESCRIPTION
**Pull request by joverlee521**
## Description of proposed changes

Add new Nextstrain clades 24A and 24B, following up on https://github.com/nextstrain/ncov/pull/1103. 
See commits for details. 

## Checklist

- [x] Checks pass
- [x] [Test run]
  - [x] https://nextstrain.github.io/forecasts-viz/?dataset=https://data.nextstrain.org/files/workflows/forecasts-ncov/trial/add-24A-24B/gisaid/pango_lineages/global/mlr/latest_results.json
  - [x] https://nextstrain.github.io/forecasts-viz/?dataset=https://data.nextstrain.org/files/workflows/forecasts-ncov/trial/add-24A-24B/gisaid/nextstrain_clades/global/mlr/latest_results.json

### CODE REVIEW

**Comment by joverlee521** [comment]
Ah, right the test run completed successfully but the [trial results](https://nextstrain.github.io/forecasts-viz/?dataset=https://data.nextstrain.org/files/workflows/forecasts-ncov/trial/add-24A-24B/gisaid/nextstrain_clades/global/mlr/2024-04-08_results.json) does not include 24A/24B because they are not in the clade counts yet. 

Will have to wait on the release of the new Nextclade dataset and full re-run of ncov-ingest to see these new clades come through.

**Comment by corneliusroemer** [comment]
There should be just a few new clade calls (not yet all as I forgot full run), enough to test, so I triggered test runs again. https://github.com/nextstrain/forecasts-ncov/actions/runs/8705257996

It's probably worth merging asap as the lack of new clades causes some issues:
image

**Review by corneliusroemer — APPROVED** [review]

**Comment by corneliusroemer** [comment]
Coloring works - we're just waiting for the updated data
image

**Comment by joverlee521** [comment]
[Force-pushed](https://github.com/nextstrain/forecasts-ncov/compare/76117487e5073d03af756859e01c9b81127625dd..66f0ea31569d5218d6c8e87ecb2a5d5363f4c080) to include changes to the viz app to update the pivot clade. 

Merging now since today's ncov-ingest run will be a full re-run to include the new Nextstrain clades ([Slack](https://bedfordlab.slack.com/archives/CSKMU6YUC/p1713269031431569)).

**Pull request merged**
